from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy.orm import Session

from riool_service.database.db_utils import get_engine
from riool_service.database.models.base import Base
from riool_service.database.models.planning_assignment import (
    PlanningAssignment,
    PlanningAssignmentSource,
    PlanningAssignmentStatus,
)
from riool_service.database.models.planning_run import (
    PlanningRun,
    PlanningRunStatus,
    PlanningRunTrigger,
)
from riool_service.database.models.tickets import Ticket, TicketStatus
from riool_service.services.planning_ai.models import PlanningConfig, PlanningSolution
from riool_service.services.planning_ai.optimizer import InitialRouteOptimizer
from riool_service.services.planning_ai.routing import get_planning_route_matrix
from riool_service.services.planning_ai.selection import load_available_technicians, load_candidate_tickets


class PlanningAiError(ValueError):
    pass


def ensure_planning_ai_tables() -> None:
    Base.metadata.create_all(get_engine())


def create_initial_planning_proposal(session: Session, payload: dict[str, Any]) -> dict[str, Any]:
    config = _config_from_payload(payload)
    technicians = load_available_technicians(session, config)
    tickets = load_candidate_tickets(session, config, technicians)
    matrix = get_planning_route_matrix(
        session,
        technicians,
        tickets,
        refresh_cache=config.refresh_route_cache,
    )
    optimizer = InitialRouteOptimizer(
        config=config,
        technicians=technicians,
        tickets=tickets,
        matrix=matrix,
    )
    solution = optimizer.optimize()
    return _solution_as_dict(config, optimizer, solution)


def run_initial_planning(session: Session, payload: dict[str, Any]) -> dict[str, Any]:
    config = _config_from_payload(payload)
    technicians = load_available_technicians(session, config)
    tickets = load_candidate_tickets(session, config, technicians)
    matrix = get_planning_route_matrix(
        session,
        technicians,
        tickets,
        refresh_cache=config.refresh_route_cache,
    )
    optimizer = InitialRouteOptimizer(
        config=config,
        technicians=technicians,
        tickets=tickets,
        matrix=matrix,
    )
    solution = optimizer.optimize()

    planning_run = PlanningRun(
        branch_id=config.branch_id,
        trigger_type=PlanningRunTrigger.DAILY_START,
        status=PlanningRunStatus.RUNNING,
        planned_date=config.planned_date,
        started_at=datetime.utcnow(),
        notes="Initial planning generated by multi-start randomized cheapest insertion + local search.",
    )
    session.add(planning_run)
    session.flush()

    planned_ticket_ids: list[int] = []
    for technician_id, route in solution.routes.items():
        stops = optimizer.build_stops(solution, technician_id)
        for sequence_order, stop in enumerate(stops, start=1):
            assignment = PlanningAssignment(
                planning_run_id=planning_run.id,
                branch_id=config.branch_id,
                technician_id=technician_id,
                ticket_id=stop.ticket.id,
                sequence_order=sequence_order,
                planned_start_at=stop.planned_start_at,
                planned_end_at=stop.planned_end_at,
                estimated_duration_minutes=stop.ticket.service_minutes,
                estimated_travel_minutes_before=stop.travel_minutes_before,
                estimated_distance_km_before=stop.distance_km_before,
                status=PlanningAssignmentStatus.PLANNED,
                source=PlanningAssignmentSource.AI,
            )
            session.add(assignment)
            planned_ticket_ids.append(stop.ticket.id)

    if planned_ticket_ids:
        for ticket in session.query(Ticket).filter(Ticket.id.in_(planned_ticket_ids)).all():
            ticket.status = TicketStatus.PLANNED

    planning_run.status = PlanningRunStatus.COMPLETED
    planning_run.completed_at = datetime.utcnow()
    planning_run.score_total_distance_km = round(solution.total_distance_km, 3)
    planning_run.score_total_travel_minutes = solution.total_travel_minutes
    planning_run.score_completed_tickets = solution.completed_tickets
    planning_run.score_unplanned_tickets = len(solution.unplanned_ticket_ids)

    result = _solution_as_dict(config, optimizer, solution)
    result["planning_run_id"] = planning_run.id
    return result


def _config_from_payload(payload: dict[str, Any]) -> PlanningConfig:
    planned_date = payload.get("planned_date") or datetime.utcnow()
    if isinstance(planned_date, str):
        planned_date = datetime.fromisoformat(planned_date.replace("Z", "+00:00"))
    if not isinstance(planned_date, datetime):
        raise PlanningAiError("planned_date must be a datetime or ISO datetime string")

    branch_id = int(payload.get("branch_id") or 1)
    return PlanningConfig(
        branch_id=branch_id,
        planned_date=planned_date,
        max_candidates_per_technician=int(payload.get("max_candidates_per_technician") or 10),
        initial_non_urgent_minutes_per_technician=int(payload.get("initial_non_urgent_minutes_per_technician") or 360),
        default_service_minutes=int(payload.get("default_service_minutes") or 60),
        multi_start_iterations=int(payload.get("multi_start_iterations") or 40),
        local_search_iterations=int(payload.get("local_search_iterations") or 250),
        random_seed=payload.get("random_seed", 42),
        refresh_route_cache=bool(payload.get("refresh_route_cache", False)),
        low_priority_max_extra_travel_minutes=int(payload.get("low_priority_max_extra_travel_minutes") or 35),
    )


def _solution_as_dict(
    config: PlanningConfig,
    optimizer: InitialRouteOptimizer,
    solution: PlanningSolution,
) -> dict[str, Any]:
    routes = []
    for technician_id, route in solution.routes.items():
        stops = optimizer.build_stops(solution, technician_id)
        routes.append(
            {
                "technician_id": technician_id,
                "technician_name": route.technician.name,
                "start_location_id": route.technician.start_location_id,
                "end_location_id": route.technician.end_location_id,
                "workday_start_minutes": route.technician.workday_start_minutes,
                "workday_end_minutes": route.technician.workday_end_minutes,
                "stops": [stop.as_dict() for stop in stops],
                "ticket_count": len(stops),
                "total_travel_minutes": _route_travel_minutes(stops),
                "total_distance_km": round(_route_distance_km(stops), 3),
            }
        )

    unplanned = []
    for ticket_id in sorted(solution.unplanned_ticket_ids):
        ticket = optimizer.ticket_by_id[ticket_id]
        unplanned.append(
            {
                "ticket_id": ticket.id,
                "urgency": ticket.urgency.value,
                "deadline_at": ticket.deadline_at.isoformat(),
                "subject": ticket.subject,
                "address": ticket.address,
                "reason": "No feasible route position found within SLA/workday/capacity rules",
            }
        )

    return {
        "algorithm": "multi_start_randomized_cheapest_insertion_plus_local_search",
        "branch_id": config.branch_id,
        "planned_date": config.planned_date.isoformat(),
        "score": round(solution.score, 3),
        "summary": {
            "completed_tickets": solution.completed_tickets,
            "unplanned_tickets": len(solution.unplanned_ticket_ids),
            "sla_misses": solution.sla_misses,
            "overtime_minutes": solution.overtime_minutes,
            "total_travel_minutes": solution.total_travel_minutes,
            "total_distance_km": round(solution.total_distance_km, 3),
            "multi_start_iterations": config.multi_start_iterations,
            "local_search_iterations": config.local_search_iterations,
            "random_seed": config.random_seed,
        },
        "design_choices": [
            "Multiple randomized start plans are tried to avoid all nearby-home mechanics staying in the same area.",
            "Each start plan is improved with move, swap and reorder operations.",
            "Low-priority tickets are added only when they fit well and do not cause SLA/workday issues.",
            "Urgent and earliest-deadline tickets are protected first.",
        ],
        "routes": routes,
        "unplanned_tickets": unplanned,
        "notes": solution.algorithm_notes,
    }


def _route_travel_minutes(stops: list[Any]) -> int:
    return sum(stop.travel_minutes_before for stop in stops)


def _route_distance_km(stops: list[Any]) -> float:
    return sum(stop.distance_km_before for stop in stops)
